[package]
name = "pomiar_myszy"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "1.0.0"
piston2d-graphics = "0.44.0"
pistoncore-glfw_window = "0.81.0"
glfw = "0.56.0"
piston2d-opengl_graphics = "0.85.0"
rand = "0.9.0"
